### ISSUE TITLE
Should i be Worry? or NOT?

### ISSUE THREAD

**Issue by akototanga** [RatPoison-dev/RatPoison#778]
idk but it kinda confuse me if should i be run this on as admin or not?
any suggestions?
![2az](https://user-images.githubusercontent.com/83336116/117579839-5b633000-b127-11eb-846b-678af45a7358.jpg)

**Comment by akototanga** [comment]
well it works fine even if i dont run it as admin but what it says about the VAC bypass is the ones that worries me. 
so should i run it as admin or let it be as i how i used it?

**Comment by sotakoira** [comment]
run admin only with vac bypass so if you are using this https://github.com/danielkrupinski/VAC-Bypass-Loader

**Comment by akototanga** [comment]
> run admin only with vac bypass so if you are using this https://github.com/danielkrupinski/VAC-Bypass-Loader

does this thing still working? and how to use it?

**Comment by sotakoira** [comment]
> 
> 
> > run admin only with vac bypass so if you are using this https://github.com/danielkrupinski/VAC-Bypass-Loader
> 
> does this thing still working? and how to use it?

compile, double click on exe, log in, start csgo, inject some detected cheat and spin in mm

**Comment by SPRAVEDLIVO** [comment]
this seems to be resolved
