### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by IRyker** [RatPoison-dev/RatPoison#779]
Crashing when i use it

**Comment by thefuckingrap** [comment]
update send packets yourself or go to sleep for a bit

**Comment by whatsupdawg11** [comment]
val dwbSendPackets = 882394

**Comment by whatsupdawg11** [comment]
> update send packets yourself or go to sleep for a bit

what do we change the packet number to this time

**Comment by gunman9000** [comment]
Only crash, what is the solution? thanks

**Comment by DxxxxY** [comment]
> Only crash, what is the solution? thanks

Wait for devs to fix, think it has to do with offsets changing because of update today.

**Comment by gunman9000** [comment]
> > Only crash, what is the solution? thanks
> 
> Wait for devs to fix, think it has to do with offsets changing because of update today.

Okay. Thank you the Information.

**Comment by icalaca** [comment]
temp solution
https://github.com/RatPoison-dev/RatPoison/issues/780#issuecomment-841027181

**Comment by sotakoira** [comment]
https://github.com/frk1/hazedumper/commit/4e95be6726f85f70c722048f4462f2b54392c18b
can be closed

**Comment by lilwhessie** [comment]
> [frk1/hazedumper@4e95be6](https://github.com/frk1/hazedumper/commit/4e95be6726f85f70c722048f4462f2b54392c18b)
> can be closed

what should i do with it?

**Comment by sotakoira** [comment]
> 
> 
> > [frk1/hazedumper@4e95be6](https://github.com/frk1/hazedumper/commit/4e95be6726f85f70c722048f4462f2b54392c18b)
> > can be closed
> 
> what should i do with it?

i don't quite understand the question?

**Comment by lilwhessie** [comment]
> > > [frk1/hazedumper@4e95be6](https://github.com/frk1/hazedumper/commit/4e95be6726f85f70c722048f4462f2b54392c18b)
> > > can be closed
> > 
> > 
> > what should i do with it?
> 
> i don't quite understand the question?

can you please tell me what should i do to update it to new csgo version im using ratpoison master currently

**Comment by sotakoira** [comment]
> 
> 
> > > > [frk1/hazedumper@4e95be6](https://github.com/frk1/hazedumper/commit/4e95be6726f85f70c722048f4462f2b54392c18b)
> > > > can be closed
> > > 
> > > 
> > > what should i do with it?
> > 
> > 
> > i don't quite understand the question?
> 
> can you please tell me what should i do to update it to new csgo version im using ratpoison master currently

https://github.com/RatPoison-dev/RatPoison/archive/refs/heads/master.zip

**Comment by re317** [comment]
change "val dwbSendPackets" value to "882586" in src\main\kotlin\rat\poison\game\offsets\EngineOffsets.kt
then delete "build" folder in ratpoison main folder then relaunch "installer.exe"

**Comment by sotakoira** [comment]
> 
> 
> change "val dwbSendPackets" value to "882586" in src\main\kotlin\rat\poison\game\offsets\EngineOffsets.kt
> then delete "build" folder in ratpoison main folder then relaunch "installer.exe"

dont do this since hazedumper and jokinace been fixed
