### ISSUE TITLE
[BUG] I start csgo, then I start RatPoison (I tried with two versiona of 1.7 and one version of 1.8). Then I enter the match/aimbots training map and my screen gets black. Every time it happend I need to close the cheat in order to be able to use my pc. I will try to reply with a screenshot so you can see what I see after i close the cheat

### ISSUE THREAD

**Issue by jiperut2** [RatPoison-dev/RatPoison#780]
**Describe the bug**

**To Reproduce**
Add steps on how to reproduce this issue/bug, if you don't this issue will be closed and won't be looked into.

**Pictures/Videos**
If applicable, add screenshots or link a video to help explain your problem.

**Comment by uwuLegacy** [comment]
please provide video/image proof and a screenshot of the console output.

**Comment by jiperut2** [comment]
Loading settings...
Settings loaded
Launching...
App Title: Counter-Strike: Global Offensive
Waiting for App
Initializing overlay
Overlay initialized
Waiting for App
AL lib: (EE) alc_cleanup: 1 device not closed
Press any key to continue . . .

**Comment by jiperut2** [comment]
ingame console or the cheat black folder that runs on background?

**Comment by jiperut2** [comment]
> please provide video/image proof and a screenshot of the console output.

hi, you mean the ingame console or the ratpoison black folder that runs in background?

**Comment by codyxd** [comment]
Can confirm, having the same Issue. 
I open the game, Open Ratpoison, try to hop into a game, The game crashes and force closes. Been happening after an update today.
They updated the game again in a span of a week tf @_@

**Comment by 9191929992** [comment]
gg

**Comment by icalaca** [comment]
As a temporarily solution update the dwbSendPackets offset in your src\main\kotlin\rat\poison\game\offsets\EngineOffsets.kt file to "val dwbSendPackets = 882586"

**Comment by jiperut2** [comment]
> As a temporary solution update the dwbSendPackets offset in your src\main\kotlin\rat\poison\game\offsets\EngineOffsets.kt file to "val dwbSendPackets I do not know how to do that, can you help me please?

**Comment by icalaca** [comment]
> > As a temporary solution update the dwbSendPackets offset in your src\main\kotlin\rat\poison\game\offsets\EngineOffsets.kt file to "val dwbSendPackets I do not know how to do that, can you help me please?

Download the source code, edit the file and then execute intaller.exe to download dependencies and compile. The .jar and .bat file will be in "build\RatPoison x.x" folder

**Comment by JahsehParks** [comment]
> As a temporary solution update the dwbSendPackets offset in your src\main\kotlin\rat\poison\game\offsets\EngineOffsets.kt file to "val dwbSendPackets = 882586"

I have done this and it still doesnt work. Did i do something wrong?

**Comment by icalaca** [comment]
> > As a temporary solution update the dwbSendPackets offset in your src\main\kotlin\rat\poison\game\offsets\EngineOffsets.kt file to "val dwbSendPackets = 882586"
> 
> I have done this and it still doesnt work. Did i do something wrong?

are u sure? it was supposed to work. I'm using the source of version 1.7.1.3

**Comment by upsetkiller** [comment]
> As a temporary solution update the dwbSendPackets offset in your src\main\kotlin\rat\poison\game\offsets\EngineOffsets.kt file to "val dwbSendPackets = 882586"


i tried it as

val val dwbSendPackets = 882586 parseOffset()
and
val val dwbSendPackets = 882586

both resulted in this error

openjdk-14.0.2_windows-x64_bin.zip: 199MB [00:13, 14.3MB/s]
installer.bat is missing. Downloading.
installer.bat: 8.19kB [00:00, 23.1kB/s]
Building RatPoison...
Starting a Gradle Daemon, 1 busy and 4 stopped Daemons could not be reused, use --status for details
<-------------> 0% EXECUTING [42s]
> :compileKotlin
Terminate batch job (Y/N)?

**Comment by sotakoira** [comment]
https://github.com/frk1/hazedumper/commit/4e95be6726f85f70c722048f4462f2b54392c18b
can be closed

**Comment by re317** [comment]
change "val dwbSendPackets" value to "882586" in src\main\kotlin\rat\poison\game\offsets\EngineOffsets.kt
then delete "build" folder in ratpoison main folder then relaunch "installer.exe"

**Comment by upsetkiller** [comment]
> change "val dwbSendPackets" value to "882586" in src\main\kotlin\rat\poison\game\offsets\EngineOffsets.kt
> then delete "build" folder in ratpoison main folder then relaunch "installer.exe"


refer to my previous post , does not work ,assuming one of the two tries i did were correct
