### ISSUE TITLE
JRE 16.0.1

### ISSUE THREAD

**Issue by Adm1nWasTaken** [RatPoison-dev/RatPoison#781]
I have installed JDK 1.16.0.1 and my overlay still isen't working. The only thing that changed when i installed it is that the logo from the taskbar changed from a bat window to the ratpoison logo. I have JRE 1.8.0 and i think that it is my issue, but i don't know.

**Comment by sotakoira** [comment]
video

**Comment by Adm1nWasTaken** [comment]
@sotakoira the menu key is ins right?

**Comment by Adm1nWasTaken** [comment]
ok im stupid, menu key is f1 not insert
FFFFF

**Comment by sotakoira** [comment]
![firefox_2021-05-14_23-51-45](https://user-images.githubusercontent.com/63243610/118335196-62b38080-b50f-11eb-91ad-37bdbf97b725.png)

**Comment by marwane2001** [comment]
Is there any new version?

**Comment by sotakoira** [comment]
https://github.com/RatPoison-dev/RatPoison/archive/refs/heads/beta.zip
https://github.com/RatPoison-dev/RatPoison/archive/refs/heads/we-do-a-little.zip
