### ISSUE TITLE
[BUG] Chet Detekted

### ISSUE THREAD

**Issue by Supaflowin** [RatPoison-dev/RatPoison#783]
**Describe the bug**
Cheat Detekted
**To Reproduce**
Vacban ON Inject

**Pictures/Videos**
Injekt the cheat

**Comment by r3muxd** [comment]
penios

**Comment by thefuckingrap** [comment]
;l

**Comment by Supaflowin** [comment]
HOLY SHIT VACBAN 5 MIN AFTER INJECTION PLS HELP

**Comment by sotakoira** [comment]
https://github.com/danielkrupinski/VAC-Bypass-Loader
