### ISSUE TITLE
Is it detected by faceit anticheat?

### ISSUE THREAD

**Issue by Tenseleo** [RatPoison-dev/RatPoison#784]
Hey sorry for the bother i was just wondering if it works with faceit anticheat?

**Comment by xiorage** [comment]
no retard kys

**Comment by Tenseleo** [comment]
> no retard kys

Imagine being this fucking toxic

**Comment by Tenseleo** [comment]
> no retard kys

Imagine being this fucking toxic

**Comment by xiorage** [comment]
> 
> 
> > no retard kys
> 
> Imagine being this fucking toxic

imagine being this fucking retarded

**Comment by Tenseleo** [comment]
> > > no retard kys
> > 
> > 
> > Imagine being this fucking toxic
> 
> imagine being this fucking retarded

Imagine being a fucktard and keep ruining peoples day for fuck sake you should be the one killing yourself, fucking worthless assholes cant believe this guy can have a stable social life fucking pathetic

**Comment by DrKelapa** [comment]
Only works on MM only
