### ISSUE TITLE
[BUG] Override not saving

### ISSUE THREAD

**Issue by dacryphiliac** [RatPoison-dev/RatPoison#786]
Gun Override is not saving and I have to redo the values every time I launch Ratpoison. Everything else seems to save fine, except for Gun Override.

Playing on 1.8.5.7 Beta

**Comment by SPRAVEDLIVO** [comment]
This won't be fixed because beta is not developed anymore
Use we-do-a-little branch

**Comment by dacryphiliac** [comment]
> This won't be fixed because beta is not developed anymore
> Use we-do-a-little branch

link?

**Comment by SPRAVEDLIVO** [comment]
> > This won't be fixed because beta is not developed anymore
> > Use we-do-a-little branch
> 
> link?
> 
> also, why not update the releases?

https://github.com/RatPoison-dev/RatPoison/tree/we-do-a-little

**Comment by dacryphiliac** [comment]
> > > This won't be fixed because beta is not developed anymore
> > > Use we-do-a-little branch
> > 
> > 
> > link?
> > also, why not update the releases?
> 
> https://github.com/RatPoison-dev/RatPoison/tree/we-do-a-little

Thanks! Got it working now!
