### ISSUE TITLE
[QUESTION] Why my Cs go Crashing every game after using the new beta ratpoison

### ISSUE THREAD

**Issue by sendekaizen** [RatPoison-dev/RatPoison#790]
Hello, I have a bug in the new beta, Every game there will be a sound like a morse code , after 5 or 10 mins the csgo application will crashed, every game it will crashed, unlike the ratpoison 1.8.4.2 theres no crashing.  only the 1.8.5.7 does the crashing error

**Comment by sotakoira** [comment]
beta is abandoned, use wdal

**Comment by sendekaizen** [comment]
wdal?
whats that ?

**Comment by sotakoira** [comment]
https://github.com/RatPoison-dev/RatPoison/archive/refs/heads/we-do-a-little.zip

Precompiled builds: https://github.com/RatPoison-dev/RatPoison/actions?query=branch%3Awe-do-a-little
