### ISSUE TITLE
Installer not working. Gives a Permisssion error [BUG]

### ISSUE THREAD

**Issue by dapinaple** [RatPoison-dev/RatPoison#792]
**Describe the bug**
When Installing/Compiling the program, it give error 'PermissionError: [Errno 13] Permission denied: 'installerSettings.json' 

**To Reproduce**
To reproduce this, clone the master branch straight from github and run the installer with the installer settings below.
Installer settings:
{
    "build_folder": "build/",
    "bypass_download": false,
    "download_missing_files": true,
    "force_cheat_compile": false,
    "force_cheat_update": false,
    "force_install_jdk": false,
    "github_repo": "TheRatCode/RatPoison",
    "jdk_installation_path": "%APPDATA%",
    "jdk_link_x64": "https://download.java.net/java/GA/jdk14.0.2/205943a0976c4ed48cb16f1043c5c647/12/GPL/openjdk-14.0.2_windows-x64_bin.zip",
    "jdk_link_x86": "https://github.com/AdoptOpenJDK/openjdk14-binaries/releases/download/jdk-14.0.2%2B12/OpenJDK14U-jdk_x86-32_windows_hotspot_14.0.2_12.zip",
    "jdk_zip_name": "JDK.zip",
    "settings_directory": "settings/",
    "show_last_X_commits": 5,
    "skip_jdk_checks": `false,`
    "update_type": "call_installer"
}

**Comment by SPRAVEDLIVO** [comment]
use releases
