### ISSUE TITLE
How do I fix This,pls Help

### ISSUE THREAD

**Issue by Mystorious17272** [RatPoison-dev/RatPoison#796]
![image](https://user-images.githubusercontent.com/59741637/119793677-6de5b380-bef4-11eb-91df-eb9c6ad56e3c.png)

**Comment by Mystorious17272** [comment]
sometimes this happens
![image](https://user-images.githubusercontent.com/59741637/119794111-ddf43980-bef4-11eb-9ec9-b7ca1bdf198b.png)

**Comment by SPRAVEDLIVO** [comment]
use precompiled

**Comment by SPRAVEDLIVO** [comment]
https://github.com/RatPoison-dev/RatPoison/actions?query=event%3Apush+branch%3Awe-do-a-little
