### ISSUE TITLE
discord link?

### ISSUE THREAD

**Issue by mountaincastle47** [RatPoison-dev/RatPoison#797]
please?

**Comment by MyNameIsKodak** [comment]
I strongly recommend having a look at the README. It has lots of great information on the cheat and, you wouldn't have to make multiple issues asking questions that have already been answered.

Yours truly,
Kodak

**Comment by mountaincastle47** [comment]
> I strongly recommend having a look at the README. It has lots of great information on the cheat and, you wouldn't have to make multiple issues asking questions that have already been answered.
> 
> Yours truly,
> Kodak

*https://discord.com/api/guilds/785830829439320095/widget.png)](https://discord.gg/TGsp8SNcFZ  this doesn't work???**

**Comment by SPRAVEDLIVO** [comment]
https://dimden.dev/ratpoisonowns

**Comment by mountaincastle47** [comment]
> https://dimden.dev/ratpoisonowns

ty
