### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by evzuba** [RatPoison-dev/RatPoison#799]
Hello, when will you update RatPoison 1.7.1.3?
With this version, the game crashes on the server during the course!

**Comment by jovi-py** [comment]
yeah, i cant seem to start the cheat in game on this version, as soon as i join a lobby my game crashes.

**Comment by sotakoira** [comment]
https://github.com/RatPoison-dev/RatPoison/archive/refs/heads/master.zip

or use https://github.com/RatPoison-dev/RatPoison/archive/refs/heads/we-do-a-little.zip
