### ISSUE TITLE
when is now update coming? can't run last version. crash issue.[QUESTION]

### ISSUE THREAD

**Issue by enoy1995** [RatPoison-dev/RatPoison#800]
**Ask questions**
Ask any questions related to the project
when is now update coming? can't run last version. crash issue.

**Comment by sotakoira** [comment]
last version (we-do-a-little) works.

**Comment by SPRAVEDLIVO** [comment]
rat crash issue

**Comment by enoy1995** [comment]
> last version (we-do-a-little) works.

ya, I download that but the installer not working.
what to do

**Comment by sotakoira** [comment]
everything works perfectly

**Comment by sotakoira** [comment]
download zip from here https://github.com/RatPoison-dev/RatPoison/actions/runs/884722088

**Comment by enoy1995** [comment]
> download zip from here https://github.com/RatPoison-dev/RatPoison/actions/runs/884722088

is it safe ??

**Comment by sotakoira** [comment]
ofc not, public cheats are never safe, especially open source.
