### ISSUE TITLE
[QUESTION] DETECTION

### ISSUE THREAD

**Issue by kuresfunk** [RatPoison-dev/RatPoison#801]
Guys, i know this may be annoying, but i just wanted to ask is the cheat really detected? Can i still use it without getting VAC banned? 
Thanks for response.

**Comment by kuresfunk** [comment]
Also i use ratpoison only to legit cheat. I use Radar and Glow visuals. No aim or anything else. Dont know if this helps.

**Comment by sotakoira** [comment]
from what we have seen it seems to be based on trust not features enabled.

**Comment by kuresfunk** [comment]
> 
> 
> from what we have seen it seems to be based on trust not features enabled.

So if i have good trust factor im good to go?

**Comment by sotakoira** [comment]
run it on alt with your config for a week, if trust wont dip it should be safe
