### ISSUE TITLE
[BUG]Whenever I Open Ratposion.bat It Closes The Ratposion UI Window

### ISSUE THREAD

**Issue by ZaxAlpha** [RatPoison-dev/RatPoison#802]
Whenever I Open Ratposion.bat It Closes The Ratposion UI Window After Initializing, Whenever I Press F1 It Changes The Window To Ratposion.bat, I Got The UI Opened 1 Time And It Was INCREDIBLY Zoomed In, And Pressing The Windows Button On Your Keyboard Zooms In, Though It Defaults The Zoom After Restart But No Luck This Time.
Look At The Screenshot, There Is No Rat Poison UI Running.
![image](https://user-images.githubusercontent.com/73659023/120916165-65923300-c6c1-11eb-895e-be2b6fc06b3a.png)

**Comment by SPRAVEDLIVO** [comment]
change your resolution to fullscreen windowed

**Comment by ZaxAlpha** [comment]
> change your resolution to fullscreen windowed

but when i start ratposion it just closes the ui opener (kinda)
