### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by Blob972** [RatPoison-dev/RatPoison#803]
**Describe the bug**
When i try to install the cheat this happens on console : 

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':shadowJar'.
> Could not resolve all dependencies for configuration ':runtimeClasspath'.
   > Could not find com.kotcrab.vis:vis-ui:1.5.0-SNAPSHOT.
     Searched in the following locations:
       - https://jcenter.bintray.com/com/kotcrab/vis/vis-ui/1.5.0-SNAPSHOT/maven-metadata.xml
       - https://jcenter.bintray.com/com/kotcrab/vis/vis-ui/1.5.0-SNAPSHOT/vis-ui-1.5.0-SNAPSHOT.pom
       - https://jitpack.io/com/kotcrab/vis/vis-ui/1.5.0-SNAPSHOT/maven-metadata.xml
       - https://jitpack.io/com/kotcrab/vis/vis-ui/1.5.0-SNAPSHOT/vis-ui-1.5.0-SNAPSHOT.pom
       - https://oss.sonatype.org/content/repositories/snapshots/com/kotcrab/vis/vis-ui/1.5.0-SNAPSHOT/maven-metadata.xml
       - https://oss.sonatype.org/content/repositories/snapshots/com/kotcrab/vis/vis-ui/1.5.0-SNAPSHOT/vis-ui-1.5.0-SNAPSHOT.pom
     Required by:
         project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Then 

BUILD FAILED in 8s
Build failed. Would you like to have installer download JDK for you and try again? [Y/N] 

Then i press yes but it still not working

I had this cheat installed and working but today it said game not found so i delete the build folder and rebuild it but i cant.

Any clues ?

**Comment by sotakoira** [comment]
remove -SNAPSHOT from version in build.gradle

**Comment by Blob972** [comment]
I change this : 

buildscript {
	ext.kotlin_version = '1.4.21'
	ext.jnaVersion = '5.6.0'
	ext.gdxVersion = '1.9.14'
	ext.visuiVersion = "1.5.0-SNAPSHOT"

To : 

buildscript {
	ext.kotlin_version = '1.4.21'
	ext.jnaVersion = '5.6.0'
	ext.gdxVersion = '1.9.14'
	ext.visuiVersion = "1.5.0"

I'm a noob so i pref ask ahhah

**Comment by sotakoira** [comment]
yes

**Comment by Blob972** [comment]
U are a legend thanks :)
