### ISSUE TITLE
[BUG]Saved CFGS Not Working

### ISSUE THREAD

**Issue by ZaxAlpha** [RatPoison-dev/RatPoison#804]
I Have A Legit CFG Saved Up But Whenever I Load It, It Closes The Menu And Also Doesn't Let Me Open It Again And All Of The Features Stop Working.

**Comment by sotakoira** [comment]
not enough information

**Comment by SPRAVEDLIVO** [comment]
well crap

**Comment by ZaxAlpha** [comment]
> not enough information
> consider recording a video of your screen with all steps necessary to reproduce the issue
> 
> actually if you are using beta, download we-do-a-little instead

Turns Out That the ratpoison menu does not show on the recording(windows+g)

**Comment by sotakoira** [comment]
use obs display capture if you wanna record menu
