### ISSUE TITLE
[BUG]Aimbot And Visuals Not Working

### ISSUE THREAD

**Issue by MaybeYouShould-GetTheHeckouttaHere** [RatPoison-dev/RatPoison#807]
Aimbot And Visuals Have Stopped Working No Matter What I Try. Pls Fix.

**Comment by TheRatCode** [comment]
Can confirm latest WDAL branch is working fine

**Comment by sotakoira** [comment]
can confirm it works on 1.7.1.3, 1.8.4.1 and wdal

**Comment by SPRAVEDLIVO** [comment]
closing because no evidence was provided

**Comment by MaybeYouShould-GetTheHeckouttaHere** [comment]
Don't Worry It's Fixed
