### ISSUE TITLE
box info

### ISSUE THREAD

**Issue by jsjsjssffg** [RatPoison-dev/RatPoison#809]
I have a problem with the info box, my game crashes after enabling the info option. I found such a video https://www.youtube.com/watch?v=gckx5gd0uFg there are the same errors on it, but on version 1.8.5.7 it can not be done as in the video. does anyone know the solution to this problem.

**Comment by sotakoira** [comment]
no errors no problem as we say, include screens or videos

**Comment by SPRAVEDLIVO** [comment]
i like how yall mark your issues as bug and don't provide any usable info
we dont send your errors/logs from cheat to server

**Comment by sotakoira** [comment]
> 
> 
> i like how yall mark your issues as bug and don't provide any usable info
> we dont send your errors/logs from cheat to server

if i were to guess its https://github.com/RatPoison-dev/RatPoison/commit/0a18a59d95e7912bb837a7c059b7c2a5afa4e258#diff-268086605f5f3b4485f51089e8c90a57495c0a742f5b8d65994ffe162dcdd184

**Comment by SPRAVEDLIVO** [comment]
> > i like how yall mark your issues as bug and don't provide any usable info
> > we dont send your errors/logs from cheat to server
> 
> if i were to guess its [0a18a59#diff-268086605f5f3b4485f51089e8c90a57495c0a742f5b8d65994ffe162dcdd184](https://github.com/RatPoison-dev/RatPoison/commit/0a18a59d95e7912bb837a7c059b7c2a5afa4e258#diff-268086605f5f3b4485f51089e8c90a57495c0a742f5b8d65994ffe162dcdd184)

this is obviously it
this issue probably just simplifies to basic issue "help i cant compile the cheat"

**Comment by sotakoira** [comment]
> this is obviously it
> this issue probably just simplifies to basic issue "help i cant compile the cheat"

https://github.com/RatPoison-dev/RatPoison/actions/workflows/push.yml
