### ISSUE TITLE
[QUESTION]How Do I Change The Name Of The BAT And JAR But It Still Works

### ISSUE THREAD

**Issue by MaybeYouShould-GetTheHeckouttaHere** [RatPoison-dev/RatPoison#812]
I Want To Edit The Name Of BAT And JAR So That I Can Avoid VACations
How Do I Do It?

**Comment by sotakoira** [comment]
edit this part
![notepad_2021-07-04_15-09-24](https://user-images.githubusercontent.com/63243610/124386272-f61c5d00-dcd9-11eb-9c39-725770a4482d.png)

**Comment by MaybeYouShould-GetTheHeckouttaHere** [comment]
> edit this part
> ![notepad_2021-07-04_15-09-24](https://user-images.githubusercontent.com/63243610/124386272-f61c5d00-dcd9-11eb-9c39-725770a4482d.png)

Also Can I Use The Latest Prerelease(1.8.5.7) without using fullscreen windowed or is it still f*cking zoomed to the point where you can see atoms

**Comment by sotakoira** [comment]
It's only zoomed if you resize the game after you launch the cheat, if you set fullscreen windowed first then run the cheat it should work just fine. 1.8.5.7 crashes while loading configs though so take that into consideration.

**Comment by MaybeYouShould-GetTheHeckouttaHere** [comment]
> It's only zoomed if you resize the game after you launch the cheat, if you set fullscreen windowed first then run the cheat it should work just fine. 1.8.5.7 crashes while loading configs though so take that into consideration.
does changing the quality affect this?

**Comment by sotakoira** [comment]
i don't recall quality changing that, just resolution

**Comment by MaybeYouShould-GetTheHeckouttaHere** [comment]
> i don't recall quality changing that, just resolution

does the cheat take up computing resources?

**Comment by sotakoira** [comment]
> 
> 
> > i don't recall quality changing that, just resolution
> 
> does the cheat take up computing resources?

it does, around 8-10% cpu usage and 300 mb ram usage on my machine

**Comment by MaybeYouShould-GetTheHeckouttaHere** [comment]
> > > i don't recall quality changing that, just resolution
> > 
> > 
> > does the cheat take up computing resources?
> 
> it does, around 8-10% cpu usage and 300 mb ram usage on my machine

when will a knife changer be added?

**Comment by sotakoira** [comment]
> 
> 
> > > > i don't recall quality changing that, just resolution
> > > 
> > > 
> > > does the cheat take up computing resources?
> > 
> > 
> > it does, around 8-10% cpu usage and 300 mb ram usage on my machine
> 
> when will a knife changer be added?

never.
