### ISSUE TITLE
ratpoison we do a little not working

### ISSUE THREAD

**Issue by australianmafia** [RatPoison-dev/RatPoison#815]
Loading settings...
Settings loaded
Menu Key: Insert
Waiting for "Counter-Strike: Global Offensive" process...
Game found. Launching.
Loading VisUI...
Waiting for App "Counter-Strike: Global Offensive"
Initializing overlay
Overlay initialized!

says this and my screen turns black and opens csgo but it doesn't actually activate any of the cheats

**Comment by SPRAVEDLIVO** [comment]
switch your mode to fullscreen windowed

**Comment by australianmafia** [comment]
> switch your mode to fullscreen windowed

it is in fullscreen windowed

**Comment by SPRAVEDLIVO** [comment]
did you try to press insert

**Comment by australianmafia** [comment]
what button is that

**Comment by australianmafia** [comment]
how do you insert

**Comment by SPRAVEDLIVO** [comment]
[!image](https://i.ytimg.com/vi/HcMA4aU8_xg/maxresdefault.jpg)

**Comment by australianmafia** [comment]
okay thank you it worked

**Comment by sotakoira** [comment]
im fucking done, another dude who cant find insert
