### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by SBMRocky** [RatPoison-dev/RatPoison#818]
Waiting for "Counter-Strike: Global Offensive" process...
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Game found. Launching.
Waiting for App
Initializing overlay
Overlay initialized

**Comment by sotakoira** [comment]
get beta 1.8.5.8 from releases

**Comment by aextise** [comment]
awesome beta 1.8 is still showing this result! You're the best sotakoira!

**Comment by MaybeYouShould-GetTheHeckouttaHere** [comment]
> awesome, beta 1.8 is still showing this result! You're the best sotakoira!

the same thing happened to me on #817 (error #2)

**Comment by SPRAVEDLIVO** [comment]
what is the bug here

**Comment by sotakoira** [comment]
oh he doesnt want that slf4j shit to appear, pretty sure wdal doesnt have it

theres also a way to disable it by dumping some jar file somewhere but this isnt really an error and shit works fine

**Comment by SPRAVEDLIVO** [comment]
oh it is not a bug

**Comment by sotakoira** [comment]
#819 yawn
