### ISSUE TITLE
[QUESTION]  when ratpoison is turned on, it starts to freeze and fps drops

### ISSUE THREAD

**Issue by udansabor** [RatPoison-dev/RatPoison#820]
My game never freezes. However, when ratpoison is turned on, it starts to freeze and fps drops. And the game becomes unplayable. My graphics card is up to date. Windows 10 is installed and all versions are up to date. I think Ratpoison is also in its current version. Why is my game slowing down? and also why it works in windowed mode and not in fullscreen?

**Comment by sotakoira** [comment]
make sure console isnt spammed with failed to resolve offset, that alone dropped my fps to 70

if you wanna play fullscreen consider getting [beta](https://github.com/RatPoison-dev/RatPoison/releases/download/1.8.5.8/RatPoison-1.8.5.8.zip) with [appless mode](https://www.reddit.com/r/atpoison/wiki/index#wiki_appless) enabled.

**Comment by MyNameIsKodak** [comment]
pretty sure its the etherium miner but idk
