### ISSUE TITLE
[BUG]WDAL no flash can't be turned off

### ISSUE THREAD

**Issue by MaybeYouShould-GetTheHeckouttaHere** [RatPoison-dev/RatPoison#825]
self explanatory
no flash off = no flash still

**Comment by SPRAVEDLIVO** [comment]
just set it back to 225 or whatever it is

**Comment by sotakoira** [comment]
> 
> 
> just set it back to 225 or whatever it is

255

or

```kotlin
othersTab.enableReducedFlash.changed { _, _ ->
        if (!curSettings["ENABLE_REDUCED_FLASH"].strToBool()) {
                csgoEXE[me + flFlashMaxAlpha] = 255F           
        }
    }
```
in OthersTab.kt

**Comment by MaybeYouShould-GetTheHeckouttaHere** [comment]
> > just set it back to 225 or whatever it is
> 
> 255
> 
> or
> 
> ```kotlin
>         enableReducedFlash.changed { _, _ ->
>             if (!enableReducedFlash.isChecked) {
>                 csgoEXE[me + flFlashMaxAlpha] = 255F
>             }
>         }
> ```
> 
> in OthersTab.kt

i already did

**Comment by sotakoira** [comment]
> bruh


https://user-images.githubusercontent.com/63243610/125751526-1deac241-0368-4730-b7cd-7dab586b40e8.mp4

https://pastebin.com/raw/3MG3tntW

**Comment by MaybeYouShould-GetTheHeckouttaHere** [comment]
> > bruh
> 
>  drake.mp4 
> https://pastebin.com/raw/3MG3tntW

what do i do with that

**Comment by MaybeYouShould-GetTheHeckouttaHere** [comment]
>>>>>>>>>9
>>>>>>>>8
>>>>>>>7
>>>>>>6
>>>>>5
>>>>4
>>>3
>>2
>1
0

**Comment by SPRAVEDLIVO** [comment]
> > > bruh
> > 
> > 
> > drake.mp4
> > https://pastebin.com/raw/3MG3tntW
> 
> what do i do with that

this is drake
