### ISSUE TITLE
Glow ESP, not through walls

### ISSUE THREAD

**Issue by snitasss** [RatPoison-dev/RatPoison#826]
Is it possible to use glow esp just to highlight players and not see through walls? I don't want to use chams because they modify cvar.

**Comment by sotakoira** [comment]
yes, set to visible

**Comment by snitasss** [comment]
Thank you, how do I open that overlay?

**Comment by sotakoira** [comment]
uh.. with a menu key?

**Comment by snitasss** [comment]
What is the menu key?

**Comment by sotakoira** [comment]
f1 by default in 1.7
insert in 1.8

how did you use this cheat without knowing this?

**Comment by snitasss** [comment]
I just ran the cheat and used notepad + for the scripts

**Comment by sotakoira** [comment]
https://github.com/RatPoison-dev/RatPoison/blob/9c2d0b64924f3e6e757e6237088850dbb259abc4/settings/GlowEsp.txt#L5
to VISIBLE

**Comment by snitasss** [comment]
Thank you so much man <3
