### ISSUE TITLE
No me funciona

### ISSUE THREAD

**Issue by Leedger** [RatPoison-dev/RatPoison#828]
Hola, soy nuevo en esto, ya lo he descargado y a funcionado correctamente , pero ahora cuando ejecuto el programa se habre pero dentro de la partida no funciona

**Comment by thefuckingrap** [comment]
![microsoft-hackathon-hackathon](https://user-images.githubusercontent.com/68853992/125904012-e9bd1ca9-45ab-44e6-ac93-58aad4873dfe.gif)

**Comment by SPRAVEDLIVO** [comment]
speak english

**Comment by sotakoira** [comment]
![image](https://user-images.githubusercontent.com/63243610/126012635-deeec5ad-49a8-45ce-88bb-2a9061204063.png)
https://www.deepl.com/en/translator

**Comment by Leedger** [comment]
What went wrong:
Could not determine the dependencies of task ':shadowJar'.
> Could not resolve all dependencies for configuration ':runtimeClasspath'.
   > Could not find com.badlogicgames.gdx:gdx:1.9.13-SNAPSHOT.
     Searched in the following locations:
       - https://jcenter.bintray.com/com/badlogicgames/gdx/gdx/1.9.13-SNAPSHOT/maven-metadata.xml
       - https://jcenter.bintray.com/com/badlogicgames/gdx/gdx/1.9.13-SNAPSHOT/gdx-1.9.13-SNAPSHOT.pom
       - https://jitpack.io/com/badlogicgames/gdx/gdx/1.9.13-SNAPSHOT/maven-metadata.xml
       - https://jitpack.io/com/badlogicgames/gdx/gdx/1.9.13-SNAPSHOT/gdx-1.9.13-SNAPSHOT.pom
       - https://oss.sonatype.org/content/repositories/snapshots/com/badlogicgames/gdx/gdx/1.9.13-SNAPSHOT/maven-metadata.xml
       - https://oss.sonatype.org/content/repositories/snapshots/com/badlogicgames/gdx/gdx/1.9.13-SNAPSHOT/gdx-1.9.13-SNAPSHOT.pom
     Required by:
         project :
   > Could not find com.badlogicgames.gdx:gdx-box2d:1.9.13-SNAPSHOT.
     Searched in the following locations:
       - https://jcenter.bintray.com/com/badlogicgames/gdx/gdx-box2d/1.9.13-SNAPSHOT/maven-metadata.xml
       - https://jcenter.bintray.com/com/badlogicgames/gdx/gdx-box2d/1.9.13-SNAPSHOT/gdx-box2d-1.9.13-SNAPSHOT.pom
       - https://jitpack.io/com/badlogicgames/gdx/gdx-box2d/1.9.13-SNAPSHOT/maven-metadata.xml
       - https://jitpack.io/com/badlogicgames/gdx/gdx-box2d/1.9.13-SNAPSHOT/gdx-box2d-1.9.13-SNAPSHOT.pom
       - https://oss.sonatype.org/content/repositories/snapshots/com/badlogicgames/gdx/gdx-box2d/1.9.13-SNAPSHOT/maven-metadata.xml
       - https://oss.sonatype.org/content/repositories/snapshots/com/badlogicgames/gdx/gdx-box2d/1.9.13-SNAPSHOT/gdx-box2d-1.9.13-SNAPSHOT.pom
     Required by:
         project :
   > Could not find com.badlogicgames.gdx:gdx-backend-lwjgl3:1.9.13-SNAPSHOT.
     Searched in the following locations:
       - https://jcenter.bintray.com/com/badlogicgames/gdx/gdx-backend-lwjgl3/1.9.13-SNAPSHOT/maven-metadata.xml
       - https://jcenter.bintray.com/com/badlogicgames/gdx/gdx-backend-lwjgl3/1.9.13-SNAPSHOT/gdx-backend-lwjgl3-1.9.13-SNAPSHOT.pom
       - https://jitpack.io/com/badlogicgames/gdx/gdx-backend-lwjgl3/1.9.13-SNAPSHOT/maven-metadata.xml
       - https://jitpack.io/com/badlogicgames/gdx/gdx-backend-lwjgl3/1.9.13-SNAPSHOT/gdx-backend-lwjgl3-1.9.13-SNAPSHOT.pom
       - https://oss.sonatype.org/content/repositories/snapshots/com/badlogicgames/gdx/gdx-backend-lwjgl3/1.9.13-SNAPSHOT/maven-metadata.xml
       - https://oss.sonatype.org/content/repositories/snapshots/com/badlogicgames/gdx/gdx-backend-lwjgl3/1.9.13-SNAPSHOT/gdx-backend-lwjgl3-1.9.13-SNAPSHOT.pom
     Required by:
         project :
   > Could not find com.badlogicgames.gdx:gdx-platform:1.9.13-SNAPSHOT.
     Searched in the following locations:
       - https://jcenter.bintray.com/com/badlogicgames/gdx/gdx-platform/1.9.13-SNAPSHOT/maven-metadata.xml
       - https://jcenter.bintray.com/com/badlogicgames/gdx/gdx-platform/1.9.13-SNAPSHOT/gdx-platform-1.9.13-SNAPSHOT.pom
       - https://jitpack.io/com/badlogicgames/gdx/gdx-platform/1.9.13-SNAPSHOT/maven-metadata.xml
       - https://jitpack.io/com/badlogicgames/gdx/gdx-platform/1.9.13-SNAPSHOT/gdx-platform-1.9.13-SNAPSHOT.pom
       - https://oss.sonatype.org/content/repositories/snapshots/com/badlogicgames/gdx/gdx-platform/1.9.13-SNAPSHOT/maven-metadata.xml
       - https://oss.sonatype.org/content/repositories/snapshots/com/badlogicgames/gdx/gdx-platform/1.9.13-SNAPSHOT/gdx-platform-1.9.13-SNAPSHOT.pom
     Required by:
         project :
   > Could not find com.badlogicgames.gdx:gdx-box2d-platform:1.9.13-SNAPSHOT.
     Searched in the following locations:
       - https://jcenter.bintray.com/com/badlogicgames/gdx/gdx-box2d-platform/1.9.13-SNAPSHOT/maven-metadata.xml
       - https://jcenter.bintray.com/com/badlogicgames/gdx/gdx-box2d-platform/1.9.13-SNAPSHOT/gdx-box2d-platform-1.9.13-SNAPSHOT.pom
       - https://jitpack.io/com/badlogicgames/gdx/gdx-box2d-platform/1.9.13-SNAPSHOT/maven-metadata.xml
       - https://jitpack.io/com/badlogicgames/gdx/gdx-box2d-platform/1.9.13-SNAPSHOT/gdx-box2d-platform-1.9.13-SNAPSHOT.pom
       - https://oss.sonatype.org/content/repositories/snapshots/com/badlogicgames/gdx/gdx-box2d-platform/1.9.13-SNAPSHOT/maven-metadata.xml
       - https://oss.sonatype.org/content/repositories/snapshots/com/badlogicgames/gdx/gdx-box2d-platform/1.9.13-SNAPSHOT/gdx-box2d-platform-1.9.13-SNAPSHOT.pom
     Required by:
         project :
   > Could not find com.badlogicgames.gdx:gdx-freetype-platform:1.9.13-SNAPSHOT.
     Searched in the following locations:
       - https://jcenter.bintray.com/com/badlogicgames/gdx/gdx-freetype-platform/1.9.13-SNAPSHOT/maven-metadata.xml
       - https://jcenter.bintray.com/com/badlogicgames/gdx/gdx-freetype-platform/1.9.13-SNAPSHOT/gdx-freetype-platform-1.9.13-SNAPSHOT.pom
       - https://jitpack.io/com/badlogicgames/gdx/gdx-freetype-platform/1.9.13-SNAPSHOT/maven-metadata.xml
       - https://jitpack.io/com/badlogicgames/gdx/gdx-freetype-platform/1.9.13-SNAPSHOT/gdx-freetype-platform-1.9.13-SNAPSHOT.pom
       - https://oss.sonatype.org/content/repositories/snapshots/com/badlogicgames/gdx/gdx-freetype-platform/1.9.13-SNAPSHOT/maven-metadata.xml
       - https://oss.sonatype.org/content/repositories/snapshots/com/badlogicgames/gdx/gdx-freetype-platform/1.9.13-SNAPSHOT/gdx-freetype-platform-1.9.13-SNAPSHOT.pom
     Required by:
         project :
   > Could not find com.badlogicgames.gdx:gdx-freetype:1.9.13-SNAPSHOT.
     Searched in the following locations:
       - https://jcenter.bintray.com/com/badlogicgames/gdx/gdx-freetype/1.9.13-SNAPSHOT/maven-metadata.xml
       - https://jcenter.bintray.com/com/badlogicgames/gdx/gdx-freetype/1.9.13-SNAPSHOT/gdx-freetype-1.9.13-SNAPSHOT.pom
       - https://jitpack.io/com/badlogicgames/gdx/gdx-freetype/1.9.13-SNAPSHOT/maven-metadata.xml
       - https://jitpack.io/com/badlogicgames/gdx/gdx-freetype/1.9.13-SNAPSHOT/gdx-freetype-1.9.13-SNAPSHOT.pom
       - https://oss.sonatype.org/content/repositories/snapshots/com/badlogicgames/gdx/gdx-freetype/1.9.13-SNAPSHOT/maven-metadata.xml
       - https://oss.sonatype.org/content/repositories/snapshots/com/badlogicgames/gdx/gdx-freetype/1.9.13-SNAPSHOT/gdx-freetype-1.9.13-SNAPSHOT.pom
     Required by:
         project :
   > Could not find com.badlogicgames.gdx:gdx:1.9.13-SNAPSHOT.
     Searched in the following locations:
       - https://jcenter.bintray.com/com/badlogicgames/gdx/gdx/1.9.13-SNAPSHOT/maven-metadata.xml
       - https://jcenter.bintray.com/com/badlogicgames/gdx/gdx/1.9.13-SNAPSHOT/gdx-1.9.13-SNAPSHOT.pom
       - https://jitpack.io/com/badlogicgames/gdx/gdx/1.9.13-SNAPSHOT/maven-metadata.xml
       - https://jitpack.io/com/badlogicgames/gdx/gdx/1.9.13-SNAPSHOT/gdx-1.9.13-SNAPSHOT.pom
       - https://oss.sonatype.org/content/repositories/snapshots/com/badlogicgames/gdx/gdx/1.9.13-SNAPSHOT/maven-metadata.xml
       - https://oss.sonatype.org/content/repositories/snapshots/com/badlogicgames/gdx/gdx/1.9.13-SNAPSHOT/gdx-1.9.13-SNAPSHOT.pom
     Required by:
         project : > com.kotcrab.vis:vis-ui:1.4.7

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by Leedger** [comment]
sorry I get that when I try to download it again in alpha. the installation does not finish, it remains at 56%

**Comment by Leedger** [comment]
java.lang.IllegalStateException: Failed to resolve offset
        at rat.poison.game.offsets.Offset$address$2.invoke(Offset.kt:44)
        at rat.poison.game.offsets.Offset$address$2.invoke(Offset.kt:12)
        at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
        at rat.poison.game.offsets.Offset.getAddress(Offset.kt)
        at rat.poison.game.offsets.Offset.getValue(Offset.kt:51)
        at rat.poison.game.offsets.EngineOffsets.getDwViewAngles(EngineOffsets.kt)
        at rat.poison.game.ClientStateKt.angle(ClientState.kt:11)
        at rat.poison.scripts.StrafeHelperKt$strafeHelper$$inlined$every$1.run(Every.kt:31)
        at java.base/java.lang.Thread.run(Thread.java:832)


I do not understand how to solve this since the program can be executed, but when entering a game it closes

I thank you if you can help me

**Comment by sotakoira** [comment]
#813

**Comment by Leedger** [comment]
bro there is the solution?

**Comment by sotakoira** [comment]
there is, did you follow the link or just gonna keep talking to yourself here

**Comment by MyNameIsKodak** [comment]
hola
