### ISSUE TITLE
I got vac, thank you

### ISSUE THREAD

**Issue by steeeeeeee** [RatPoison-dev/RatPoison#831]
few days ago i dowmnload ratpoisen and used it, after using it nothing happened except some minor headaches, then i went to bed. in the night i felt bit unwell and woke up, i was feeling very warm and uncomfortable. next mornin i go see doctor and he told me i got vac:( i got vaccinated by using ratto’s white thick poison . so thank u i hope its also producing covid antibodies in my body.

**Comment by MyNameIsKodak** [comment]
Stfu

**Comment by thefuckingrap** [comment]
![mBHJMgJ](https://user-images.githubusercontent.com/68853992/126082616-36eebf09-b842-4662-a120-c11b61d443d3.png)

**Comment by SPRAVEDLIVO** [comment]
oooo you are becoming sussy femboy you will wear silly outfits

**Comment by SPRAVEDLIVO** [comment]
np

**Comment by SPRAVEDLIVO** [comment]
warning is in master readme
