### ISSUE TITLE
[BUG] Skin changer does not work after update

### ISSUE THREAD

**Issue by kirill-21** [RatPoison-dev/RatPoison#842]
I guess it's because this part (csgoEXE.int(clientState + 0x174) > 0 && shouldPostProcess) retrieves an address with a minus

**Comment by sotakoira** [comment]
could you elaborate

https://user-images.githubusercontent.com/63243610/134778119-37c68060-f7ee-45c9-9194-f6fbf76ecfae.mp4

**Comment by kirill-21** [comment]
A bug maybe, thank you
