### ISSUE TITLE
[QUESTION] Weird message when i open the cheat

### ISSUE THREAD

**Issue by cosmopolitanism3** [RatPoison-dev/RatPoison#844]
When i try to start the cheat it says:

"SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details."

It never used to happen to me before, is there any way to fix it?

**Comment by sotakoira** [comment]
ignore it or do https://github.com/RatPoison-dev/RatPoison/commit/333ec2d20c875a9141ed136f0c03c74466c371db to hide it
