### ISSUE TITLE
[QUESTION] Is it detected now ?

### ISSUE THREAD

**Issue by NOCLAF1337** [RatPoison-dev/RatPoison#854]
https://www.talkesport.com/news/csgo/vac-detects-popular-csgo-cheat/

> TalkEsport reported about a popular CS:GO cheat (RatPoison) that was detected by the Valve Anti-Cheat (VAC)

**Comment by SPRAVEDLIVO** [comment]
the article was published when it wasn't detected
it was detected after article and a lot of hyper around the project.
so, yes, it is detected

**Comment by sotakoira** [comment]
it's been detected since 26th may 2021
