### ISSUE TITLE
It does not work

### ISSUE THREAD

**Issue by Leedger** [RatPoison-dev/RatPoison#856]
Hello, how are you all? A few days ago I tried to start the rat but I get this. and when I press the key the program closes, can you give me any help? thank you
![rat](https://user-images.githubusercontent.com/87503351/145682699-19da18d8-fc0a-4f64-97bf-ff0dbd8bc612.png)

**Comment by sotakoira** [comment]
semifix without backtrack working, while we figure out why backtrack times out the user on pistol rounds
https://github.com/sotakoira/RatPoison/suites/4626266606/artifacts/125238246

**Comment by Leedger** [comment]
@sotakoira should I download that link?

**Comment by sotakoira** [comment]
read announcements on discord
![image](https://user-images.githubusercontent.com/63243610/145683090-71092ae9-b820-43a2-931e-4ee657608749.png)

**Comment by Leedger** [comment]
@sotakoira  thank you very much problem solved

**Comment by SPRAVEDLIVO** [comment]
!rat

**Comment by anishbajpai91** [comment]
worked ty
