### ISSUE TITLE
[QUESTION] It doesn't work for me

### ISSUE THREAD

**Issue by nebechodzz** [RatPoison-dev/RatPoison#858]
Did everything in common issues, but everytime nothing happens after i open the bat file, it loads fine,, but there is nothing in csgo

**Comment by nebechodzz** [comment]
![image](https://user-images.githubusercontent.com/96952815/147856616-8e9c03b6-a3bd-4cc3-8ae1-65258d2e362a.png)
![image](https://user-images.githubusercontent.com/96952815/147856621-04475fc3-428f-4817-b50d-789e2cdf9c81.png)

**Comment by sotakoira** [comment]
read the #856 issue and don't make so many issues about one problem

**Comment by nebechodzz** [comment]
bhut what next, there is file and when i try to use installer in that new file it instantly closes

**Comment by nebechodzz** [comment]
im sorry, but i never used this before so i dont rly know what to do :(

**Comment by sotakoira** [comment]
it worked the last time some dude told me it doesnt, so u should show errors

**Comment by nebechodzz** [comment]
I don't know what am i supposed to do after I install the zip..

**Comment by nebechodzz** [comment]
![image](https://user-images.githubusercontent.com/96952815/147859573-bfa88ebe-9397-4092-95f8-f6cf02426115.png)
it shows this and after i choose to rename files etc. nothing happens in game

**Comment by nebechodzz** [comment]
I just installed it and opened the build.bat in it

**Comment by sotakoira** [comment]
installer.bat not build.bat

**Comment by nebechodzz** [comment]
I did that before, forgot to mention

**Comment by nebechodzz** [comment]
but it insta closed i think as well, both installerse just insta closed

**Comment by sotakoira** [comment]
open the installer bat from cmd and post what shows under
might be antivirus removing the file

**Comment by sotakoira** [comment]
or just use the precompiled build from other issue

**Comment by nebechodzz** [comment]
it says i cannot open this on my pc

**Comment by nebechodzz** [comment]
![image](https://user-images.githubusercontent.com/96952815/147860178-61cef076-c61d-4d17-b8ad-267b23b438ea.png)

**Comment by nebechodzz** [comment]
the old installer opened just fine, so i dk whats wrong with this one

**Comment by sotakoira** [comment]
what happens when you download this and unpack https://github.com/sotakoira/RatPoison/suites/4626266606/artifacts/125238246

unpack until you see this 
![image](https://user-images.githubusercontent.com/63243610/147860733-5798c944-fdc3-42cf-b041-31195fed12cd.png)

then start ratpoison bat when you have game running
