### ISSUE TITLE
[QUESTION] Is it possible to compile the entire thing by hand in VSC?

### ISSUE THREAD

**Issue by sadesguy** [RatPoison-dev/RatPoison#859]
###### pls no hate

**Comment by MyNameIsKodak** [comment]
he not DLL file xD

**Comment by SPRAVEDLIVO** [comment]
compiling kotlin into dll rn

**Comment by SPRAVEDLIVO** [comment]
java and kotlin produce .jar file(s) as build artifact
the ide to do to so is intellij idea community or eclipse
