### ISSUE TITLE
How do I enable backtrack?

### ISSUE THREAD

**Issue by getgle** [RatPoison-dev/RatPoison#860]
It's always disabled by default and the checkbox to enable it is greyed out in the UI
how do I enable it? is there a config file I need to edit

`Loading settings...
Settings loaded
Launching...
Backtrack disabled
App Title: Counter-Strike: Global Offensive - Direct3D 9
Waiting for App
Initializing overlay
Overlay initialized`

**Comment by SPRAVEDLIVO** [comment]
no way you can, feature broke long time ago

**Comment by getgle** [comment]
ok thanks
