### ISSUE TITLE
i love men

### ISSUE THREAD

**Issue by sarahdumby** [RatPoison-dev/RatPoison#861]
i love men

**Comment by sotakoira** [comment]
![firefox_Bq51OyFGzq](https://user-images.githubusercontent.com/63243610/168621951-abe89e64-1779-4a96-9349-4c1809ea9eb1.png)

**Comment by sarahdumby** [comment]
mb ![image](https://user-images.githubusercontent.com/83651474/168627977-a589f813-83d3-4df5-b9d8-4dac306d29e4.png)

**Comment by getgle** [comment]
[
![angel](https://user-images.githubusercontent.com/26177157/168637913-eaefb4db-0cf9-437e-93d0-2bbd31f354d0.gif)
](url)
